### PR TITLE
Source Serif

### PR DESCRIPTION
**Pull request by Nidite**

### CODE REVIEW

**Comment by Fripe070** [comment]
Relevant license: [adobe-fonts/source-serif LICENSE.md](https://github.com/adobe-fonts/source-serif/blob/6e2784a47aad721b1980b03df9c9f318da15ad10/LICENSE.md)
It is SIL Open Font License 1.1, with a trademark notice added.

Without having looked all too much into it, this is the only thing that might potentially be an issue? I think it's fine though.
> Copyright 2014 - 2023 Adobe (http://www.adobe.com/), with Reserved Font Name ‘Source’. All Rights Reserved. Source is a trademark of Adobe in the United States and/or other countries.

**Comment by randomairborne** [comment]
I wonder if i would be allowed to offer it as “Adobe Source Serif”

**Comment by Fripe070** [comment]
I’m quite certain we are allowed to keep the font’s name as just “Source Serif”. I think we’d only have an issue if we modified the font and redistributed it as “source”? (Which we aren’t doing)

**Comment by randomairborne** [comment]
Alright. I'll merge this in.

**Pull request merged**
